Fix: Add missing arguments to `CalledProcessError` exception (#315)
Before this change, when a post_install script failed we would get
```
raise CalledProcessError
TypeError: __init__() missing 2 required positional arguments: 'returncode' and 'cmd'
```
The correct error should look something like:
```
CalledProcessError: Command 'echo' returned non-zero exit status 1.
```

More info at:
https://docs.python.org/3/library/subprocess.html#subprocess.CalledProcessError