Fix: Add missing arguments to raised exception
Before this change, when a post_install script failed
we would get
```
raise CalledProcessError
TypeError: __init__() missing 2 required positional arguments: 'returncode' and 'cmd'
```

More info at:
https://docs.python.org/3/library/subprocess.html#subprocess.CalledProcessError